name: Run Selenium test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Firefox and Geckodriver manually
      run: |
        FIREFOX_VERSION=115.0
        GECKODRIVER_VERSION=v0.36.0

        wget -q "https://ftp.mozilla.org/pub/firefox/releases/${FIREFOX_VERSION}/linux-x86_64/en-US/firefox-${FIREFOX_VERSION}.tar.bz2"
        tar -xjf "firefox-${FIREFOX_VERSION}.tar.bz2"
        sudo mv firefox /opt/firefox
        sudo ln -sf /opt/firefox/firefox /usr/bin/firefox

        wget -q "https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VERSION}/geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz"
        tar -xzf "geckodriver-${GECKODRIVER_VERSION}-linux64.tar.gz"
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Run tests with pytest
      run: pytest
